### PR TITLE
Support various JWT signing algorithms (not only HS256 as before)

### PR DESCRIPTION
**Pull request by aksonov**
Thank you for great package. Here is PR to support various JWT signing algorithms (not only HS256 as before)

### CODE REVIEW

**Comment by zaguiini** [comment]
Thanks for the PR!

Although, how that would work? There is no place to include the public and private keypairs? The only thing it does is allowing to input the algorithm, but some algorithms require more than just a string for signing, I think.

**Comment by aksonov** [comment]
Hm... I can say definitely only about HS512 our app uses - it requires only secret key like HS256. I guess the same for HS384. 

Probably you are right about RSxxx algorithms - so we can just remove wording that your module supports them...

**Comment by zaguiini** [comment]
Can you this test for us? Make sure that it works for both `HS256` and `HS512` and then update the `README` with the correct info?

Maybe we can work in the near future to include other options, probably using `react-native-fetch-blob` to load the signing keys for the `RSxxx` algorithms.

**Comment by aksonov** [comment]
@zaguiini Done. Yes, I tested all HSxxx, works perfectly!

**Comment by zaguiini** [comment]
Thanks! I'll work with this later tonight and publish the new version. Thank you so much for the PR and I'm open for discussions about the `RS`, `ES` and `PS` signing algorithms.

**Comment by zaguiini** [comment]
Published! Version: `2.1.0` at https://unpkg.com/react-native-pure-jwt@2.1.0/

**Pull request merged**
